project:
  type: website
  output-dir: docs
  render: 
    - index.qmd

website:
  navbar:
    title: "AIMdata"
    logo: brand/logo_squares.png
    logo-href: "www.aimdata.org"
    left:
        - href: index.qmd
          text: Part One
     
    right:
        - icon: github
          href: "https://github.com/aimdata-labs"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-summary: "Show code"
    page-layout: full
    self-contained-math: true
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true

editor: source

brand: brand/_brand.yml



